// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v4.23.4
// source: rpc_get_filter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilterID uint64 `protobuf:"varint,1,opt,name=filterID,proto3" json:"filterID,omitempty"`
}

func (x *GetFilterRequest) Reset() {
	*x = GetFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterRequest) ProtoMessage() {}

func (x *GetFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterRequest.ProtoReflect.Descriptor instead.
func (*GetFilterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_filter_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilterRequest) GetFilterID() uint64 {
	if x != nil {
		return x.FilterID
	}
	return 0
}

type GetFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *GetFilterResponse) Reset() {
	*x = GetFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterResponse) ProtoMessage() {}

func (x *GetFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterResponse.ProtoReflect.Descriptor instead.
func (*GetFilterResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_filter_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilterResponse) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

var File_rpc_get_filter_proto protoreflect.FileDescriptor

var file_rpc_get_filter_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x72,
	0x70, 0x63, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x3a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x36, 0x5a, 0x34, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4e, 0x6f, 0x76, 0x69, 0x6b, 0x6f,
	0x76, 0x41, 0x6e, 0x64, 0x72, 0x65, 0x77, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2d, 0x66, 0x75,
	0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_filter_proto_rawDescOnce sync.Once
	file_rpc_get_filter_proto_rawDescData = file_rpc_get_filter_proto_rawDesc
)

func file_rpc_get_filter_proto_rawDescGZIP() []byte {
	file_rpc_get_filter_proto_rawDescOnce.Do(func() {
		file_rpc_get_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_filter_proto_rawDescData)
	})
	return file_rpc_get_filter_proto_rawDescData
}

var file_rpc_get_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_get_filter_proto_goTypes = []interface{}{
	(*GetFilterRequest)(nil),  // 0: proto.GetFilterRequest
	(*GetFilterResponse)(nil), // 1: proto.GetFilterResponse
	(*Filter)(nil),            // 2: proto.Filter
}
var file_rpc_get_filter_proto_depIdxs = []int32{
	2, // 0: proto.GetFilterResponse.filter:type_name -> proto.Filter
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_get_filter_proto_init() }
func file_rpc_get_filter_proto_init() {
	if File_rpc_get_filter_proto != nil {
		return
	}
	file_rpc_filter_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_filter_proto_goTypes,
		DependencyIndexes: file_rpc_get_filter_proto_depIdxs,
		MessageInfos:      file_rpc_get_filter_proto_msgTypes,
	}.Build()
	File_rpc_get_filter_proto = out.File
	file_rpc_get_filter_proto_rawDesc = nil
	file_rpc_get_filter_proto_goTypes = nil
	file_rpc_get_filter_proto_depIdxs = nil
}
